development:
  stripe_secret_key: 'sk_test_51IAYubBvkTbYjE6ILtKijWu6L7KK937OX9pNFVaxEJWysNcIlUpClPDYvI83xj0Ny5CHbYPvFHI47LP2MNwaTiyp00Ct8KLtRy'
  stripe_publishable_key: 'pk_test_51IAYubBvkTbYjE6IOdy5bobJZhsnzqxUNcNx2EDGV2R4lus2qkwSzXjxiw9wXxbWjcz6dPSS25UVUmRbPz3DBHni00K61l08p5'

production:
  stripe_secret_key: 'sk_live_aLvPhyGtUwlLSHvms3KhCdrL'
  stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'
